name: Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install PHP version
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.4'

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install MariaDB
        uses: YakkaDev/mariadb-actions@v1.1.0
        with:
          root pass: lotgd
          database: lotgd_test
          user: lotgd
          password: lotgd
          
      - uses: actions/checkout@v4
      
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
  
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
        
      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build webpack
        uses: borales/actions-yarn@v4
        with:
          cmd: run build

      - name: Setup database
        env:
          DATABASE_URL: mysql://lotgd:lotgd@127.0.0.1:3306/lotgd?serverVersion=10.6.18-MariaDB&charset=utf8mb4
        run: |
          bin/console doctrine:migrations:migrate first --quiet --no-interaction
          bin/console doctrine:migrations:migrate --quiet --no-interaction
          bin/console doctrine:fixtures:load --quiet --no-interaction

      - name: Run test suite
        env:
          DATABASE_URL: mysql://lotgd:lotgd@127.0.0.1:3306/lotgd_v2?serverVersion=10.6.18-MariaDB&charset=utf8mb4
        run: vendor/bin/phpunit --stop-on-failure
      
